apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-exporter
  namespace: yourNamespace
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: oracle-exporter
  template:
    metadata:
      labels:
        app: oracle-exporter
    spec:
      containers:
      - name: oracle-exporter
        args:
          - "--config=/opt/secrets/config.yaml"
          - "--metrics-folder=/opt/rules"
        image: 6fears7/multi-target-oracle-exporter:0.1.0
        ports:
        - containerPort: 9101
        volumeMounts:
          - mountPath: /opt/secrets
            name: oracle-secrets
          - mountPath: /opt/rules
            name: oracle-rules    
      volumes:
      - name: oracle-rules
        configMap:
          name: oracle-configmap
      - name: oracle-secrets
        secret:
          secretName: oracle-config